[package]
name = "qdrust-cli"
version = "0.1.1"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
chrono = "0.4"
qdrust-core = { path = "../qdrust-core", version = "0.1.1" }
rusqlite = { version = "0.32", features = ["backup"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
